# uConsole CM5: enable software volume/mute for RP1AudioOut in PipeWire.

monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.platform-rp1_audio_out_simple_card_0"
      }
    ]
    actions = {
      update-props = {
        api.alsa.soft-mixer = true
      }
    }
  }
]
