PACKAGE_NAME="uconsole-cm5"
PACKAGE_VERSION="0.1"
AUTOINSTALL="yes"

BUILT_MODULE_NAME[0]="panel-cwu50"
DEST_MODULE_LOCATION[0]="/updates/dkms"

BUILT_MODULE_NAME[1]="ocp8178_bl"
DEST_MODULE_LOCATION[1]="/updates/dkms"

BUILT_MODULE_NAME[2]="axp20x"
DEST_MODULE_LOCATION[2]="/updates/dkms"

BUILT_MODULE_NAME[3]="axp20x-i2c"
DEST_MODULE_LOCATION[3]="/updates/dkms"

BUILT_MODULE_NAME[4]="axp20x-regulator"
DEST_MODULE_LOCATION[4]="/updates/dkms"

BUILT_MODULE_NAME[5]="axp20x_battery"
DEST_MODULE_LOCATION[5]="/updates/dkms"

BUILT_MODULE_NAME[6]="axp20x_adc"
DEST_MODULE_LOCATION[6]="/updates/dkms"

BUILT_MODULE_NAME[7]="snd-soc-simple-amplifier"
DEST_MODULE_LOCATION[7]="/updates/dkms"

BUILT_MODULE_NAME[8]="axp20x-pek"
DEST_MODULE_LOCATION[8]="/updates/dkms"
